name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      working-directory : ./SoftBeckhoff
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      working-directory: ${{env:working-directory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env:working-directory}}
      run: dotnet build --configuration Release --no-restore
    
